"""Shared fixtures.

Audio fixtures are synthetic only: tones generated by ffmpeg at test time. Never commit real
voice recordings (see CLAUDE.md).
"""

from __future__ import annotations

import shutil
import subprocess
import wave
from pathlib import Path

import pytest

FFMPEG = shutil.which("ffmpeg")
HAVE_FFMPEG = FFMPEG is not None and shutil.which("ffprobe") is not None

TONE_HZ = 440
TONE_SECONDS = 2.0

_TONE = f"sine=frequency={TONE_HZ}:sample_rate=44100:duration={TONE_SECONDS}"

# name -> (extra input args, output args, filename)
_GENERATED: dict[str, tuple[list[str], list[str], str]] = {
    # Accepted formats
    "wav_pcm16_44k_stereo": ([], ["-ac", "2", "-ar", "44100", "-c:a", "pcm_s16le"], "tone.wav"),
    "wav_mulaw_8k": ([], ["-ac", "1", "-ar", "8000", "-c:a", "pcm_mulaw"], "phone.wav"),
    "flac": ([], ["-c:a", "flac"], "tone.flac"),
    "ogg_vorbis": ([], ["-c:a", "libvorbis"], "tone.ogg"),
    "ogg_opus": ([], ["-c:a", "libopus", "-b:a", "24k"], "tone.opus"),
    "mp3": ([], ["-c:a", "libmp3lame", "-b:a", "64k"], "tone.mp3"),
    "m4a_aac": ([], ["-c:a", "aac", "-b:a", "64k"], "tone.m4a"),
    # Rejected formats
    "adts_aac": ([], ["-c:a", "aac", "-f", "adts"], "tone.aac"),
    "wav_adpcm": ([], ["-c:a", "adpcm_ms"], "adpcm.wav"),
    "mp4_video": (
        ["-f", "lavfi", "-i", "testsrc=size=64x64:rate=5:duration=2"],
        ["-map", "0:a", "-map", "1:v", "-c:a", "aac", "-c:v", "mpeg4"],
        "video.mp4",
    ),
}


@pytest.fixture(scope="session")
def audio_fixtures(tmp_path_factory: pytest.TempPathFactory) -> dict[str, Path]:
    """Generate every synthetic fixture once per test session."""
    if not HAVE_FFMPEG:
        pytest.skip("ffmpeg and ffprobe are needed to generate audio fixtures")
    out_dir = tmp_path_factory.mktemp("audio")
    files: dict[str, Path] = {}
    for name, (extra_inputs, output_args, filename) in _GENERATED.items():
        path = out_dir / filename
        command = [
            FFMPEG, "-nostdin", "-hide_banner", "-loglevel", "error",
            "-f", "lavfi", "-i", _TONE,
            *extra_inputs,
            *output_args,
            "-y", str(path),
        ]  # fmt: skip
        subprocess.run(command, check=True, capture_output=True)
        files[name] = path

    empty = out_dir / "empty.wav"
    with wave.open(str(empty), "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(16_000)
    files["wav_empty"] = empty
    return files
